// utils/mapaCategorias.js
module.exports = {
  aventura: "sport",
  cultural: "cultural",
  relaxamento: "natural",
  gastronomico: "foods",
  compras: "shops",
  romantico: "architecture",
  museus: "museums",
  parques: "parks",
  vidaNoturna: "adult,nightclubs",
  toursGuiados: "tourist_facilities",
  shows: "cultural,events",
  natureza: "natural",
  praias: "beaches",
  montanhas: "mountains",
  fast_food: "fast_food",
  gourmet: "gourmet",
  vegetariano: "vegetarian",
  vegano: "vegan",
  seafood: "seafood",
  "street food": "street_food",
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
};
